name: CI/CD FOR DEV

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build
        run: mvn -B package --file pom.xml
      - name: Create build path staging
        run: mkdir staging && cp target/*.war staging
      - name: Upload math result for job
        uses: actions/upload-artifact@v1
        with:
          name: exchange_api
          path: staging
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: ${{ dd3f739a-716d-4e78-9a5f-403143705357 }}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ dd3f739a-716d-4e78-9a5f-403143705357 }}
          HEROKU_APP_NAME: jaya-exchange-api
        run: heroku plugins:install java && heroku create --no-remote && heroku deploy:war staging/exchange-0.0.1-SNAPSHOT.war --app jaya-exchange-api